name: personal_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  lottie: ^1.3.0
  material_design_icons_flutter: ^5.0.6595

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lottie/
